CREATE TABLE test_table (
    id           INT8 GENERATED BY DEFAULT AS IDENTITY,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now() NOT NULL,
    total        INT4,
    PRIMARY KEY (id)
);
