CREATE TABLE "accounts" (
    id    BIGINT                 NOT NULL,
    email CHARACTER VARYING(255) NOT NULL
);

ALTER TABLE "accounts"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "accounts_id_seq"
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
