[versions]
# Libraries
hibernate = "6.6.13.Final"
commons-lang = "3.17.0"
classgraph = "4.8.180"
hypersistence-utils = "3.9.2"
commons-collections = "4.4"
flyway = "11.3.1"
jakarta-annotation = "3.0.0"
jackson = "2.18.3"
jansi = "2.4.1"
jetbrains-annotations = "26.0.2"
jsqlparser = "5.1"
junit = "5.11.4"
logback = "1.5.16"
micronaut = "4.7.6"
opencsv = "5.10"
picocli = "4.7.6"
postgresql = "42.7.10"
reactor = "3.7.3"
slf4j = "2.0.17"
testcontainers = "1.21.0"


[libraries]
# BOMs
boms-micronaut = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut" }
boms-testcontainers = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }

# Libraries
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
commons-collections = { module = "org.apache.commons:commons-collections4", version.ref = "commons-collections" }
commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }
hypersistence-utils = { module = "io.hypersistence:hypersistence-utils-hibernate-63", version.ref = "hypersistence-utils" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jsqlparser = { module = "com.github.jsqlparser:jsqlparser", version.ref = "jsqlparser" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
