CREATE TABLE "account" (
    id                 BIGINT                                     NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT now()  NOT NULL,
    email              TEXT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT now()  NOT NULL,
    username           CHARACTER VARYING(255)      DEFAULT 'test' NOT NULL,
    login              CHARACTER VARYING(255),
    username_old       CHARACTER VARYING(255)                     NOT NULL,
    version            BIGINT                      DEFAULT 0      NOT NULL
);

ALTER TABLE "account"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "account_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE "account"
    ADD CONSTRAINT "account_pkey" PRIMARY KEY (id);

ALTER TABLE "account"
    ADD CONSTRAINT "uk_account_username" UNIQUE (username);

CREATE INDEX ix_account_email ON account USING btree(email);
